# Site settings
title: jChong
email: jChong87@gmail.com
description: jChong is a student from Long Island.
url: http://drawinghands1948.github.io
github_username: drawinghands1948

# Build settings
markdown: kramdown
permalink: pretty
